LOGGING_STATE = 3
INVALID_LOGIN = -2
SUCCESS_STATE = 1
FINISH_FRIEND = 2
NOT_MATCH_STATE = -5

FAILED_STATE = -1
WAITING_USER_STATE = -3
ALREADY_IN = -4
CHECK_COOKIE = 0

USER_INFO_KEY = "USER_INFO_KEY"